src/driver/websocket-client/index.ts

🐛 修复 WebSocket 连接在断开后不会自动重连的问题

---

src-tauri/src/utils.rs

修改了 file url 的正则表达式和文本替换
发送 file url 资源时无法正确解析

🐛 修复 file url 解析错误的问题

---

src/utils/chat.ts

🩹 用户头像链接更换为 https

---

src-tauri/src/plugins/websocket.rs

更改了请求头中的 Host 字段
请求头 Host 错误时，连接会出现 HTTP 400 错误

🐛 修复 WebSocket 无法连接到域名地址的问题

---

src-tauri/src/main.rs

🐛 修复日志时区与本地不一致的问题

---

src/exceptions/index.ts

移除了 exceptions 文件夹
在项目中没有使用，与 adapter/errors 的作用重复

🔥 移除 exceptions

---

src/adapter/behav.ts
src/adapter/onebot/v11/action.ts
src/adapter/onebot/v11/event.ts
src/adapter/scene.ts
src/components/ChatBox.vue
src/components/ChatInput.vue
src/components/ChatMessage.vue
src/components/CreateGroupForm.vue
src/components/CreateMemberForm.vue
src/components/CreateUserForm.vue
src/components/SelectUserList.vue
src/database/db.ts
src/database/index.ts
src/database/model.ts
src/stores/status.ts
src/utils/chat.ts

修改了数据模型
1. id 的类型不统一，为此产生了许多不必要的类型转换代码
2. 数据建模存在问题，部分字段不合理

♻️ 重构数据库模型

---

src/adapter/content.ts
src/adapter/onebot/v11/message.ts
src/components/ChatInput.vue
src/components/MessageContent.vue
src/utils/chat.ts

去除 mention 的 all 字段并将 user_id 重命名为 target
分成两个字段没有必要的，这增加了不必要的复杂度

🧱 修改提及消息段结构

---

src/adapter/behav.ts
src/adapter/event.ts
src/adapter/onebot/v11/event.ts
src/adapter/scene.ts
src/stores/chat.ts

调整了部分事件场景的结构，移除了事件处理器的解析策略
部分事件场景结构不合理，事件处理器的解析策略没有使用场景

♻️ 重构事件场景与事件处理器

---

README.md
src/adapter/action.ts
src/adapter/behav.ts
src/adapter/onebot/v11/action.ts
src/adapter/onebot/v11/utils.ts
src/utils/chat.ts

✨ OneBot v11 动作补全

---

src/adapter/errors.ts
src/adapter/onebot/v11/action.ts

将动作处理器运行时出现的异常返回给机器人
动作处理器运行时出现异常没有反馈，无法进行判断

✨ 添加动作处理器运行时异常

---

package.json

调整了 lint 的检查类型
lint-staged 运行 stylelint 时对于 ts 类型文件会出现错误

🔨 更新 lint 脚本

---

src/adapter/behav.ts
src/adapter/onebot/v11/action.ts
src/command/index.ts
src/components/ChatBox.vue
src/components/ChatContactItem.vue
src/stores/chat.ts

使用 Array 代替 Map 来保存聊天记录，避免使用 status.bot.id
由于 #14 的更改，导致聊天记录无法显示

🐛 修复聊天记录无法显示的问题

---

src/adapter/behav.ts
src/adapter/scene.ts
src/command/index.ts
src/components/ChatBox.vue
src/components/ChatContactItem.vue
src/components/ChatMessage.vue

使用更详细的 session 替换 talker，以更好的区分各个事件
talker 标识的区分度不足

♻️ 重构事件场景会话标识

---

src/utils/chat.ts

🐛 修复 `roleCheck` 函数判断错误的问题

---

src/components/Avatar.vue

将 img 标签的宽度也设置为 100%
在源头像图片宽度不一致的情况下，Avatar 组件在视觉上的尺寸长宽不一

🩹 修复头像组件的尺寸问题

---

src/adapter/action.ts
src/adapter/adapter.ts
src/adapter/behav.ts
src/adapter/onebot/v11/action.ts
src/adapter/onebot/v11/utils.ts
src/components/ChatBox.vue
src/stores/chat.ts

在事件创建之后直接添加
目前事件创建之后，需要手动添加事件，导致在各处留下了不必要的代码，同时也不便于事件管理

♻️ 重构事件添加流程

---

src/components/SelectUserList.vue

交换当前 Bot 与 用户的身份
无法直接交换，需要借助第三者交换身份，操作不流畅

✨ 支持交换使用的 Bot 与用户身份

---

src/adapter/behav.ts

🐛 修复好友事件的错误字段值

---

src/adapter/behav.ts
src/adapter/event.ts
src/adapter/onebot/v11/event.ts
src/adapter/scene.ts

♻️ 优化事件结构与处理

---

src/adapter/onebot/v11/action.ts
src/components/ChatMessage.vue

♻️ 使用 `status.assignBot` 替换 `status.bot.id`

---

src/driver/websocket-client/index.ts

判断请求的数据类型，返回相同数据类型的响应
一律返回 json 并不太合理，应该根据请求的数据类型自动选择

✨ WebSocket 返回与请求数据类型相同的响应

---

src/stores/chat.ts

当不是 Bot 发送的事件时，才进行上报
上报自身事件配置的判断错误，当选择不上报自身事件时，所有的事件都不会上报

🐛 修复上报自身事件的判断不正确的问题

---

package.json
pnpm-lock.yaml
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/command.rs
src-tauri/src/main.rs
src-tauri/src/server.rs
src-tauri/src/utils.rs
src/adapter/onebot/v11/message.ts
src/components/ChatInput.vue
src/database/db.ts
src/database/model.ts
src/utils/file.ts

重构了缓存文件系统，使用 sha256 替换 md5
旧有的缓存文件模式不便于支持 OneBot v12 协议

♻️ 重构缓存文件系统

---

src/views/SettingStage.vue

判断适配器是否切换，如果切换了则不重启
目前即使适配器没有切换，也依然会触发重启行为，这会造成多适配器下连接混乱错误

🐛 修复设置保存时错误的重启适配器行为

---

README.md
package.json
pnpm-lock.yaml
src-tauri/src/command.rs
src-tauri/src/main.rs
src/adapter/action.ts
src/adapter/adapter.ts
src/adapter/content.ts
src/adapter/index.ts
src/adapter/onebot/v12/action.ts
src/adapter/onebot/v12/bot.ts
src/adapter/onebot/v12/event.ts
src/adapter/onebot/v12/index.ts
src/adapter/onebot/v12/message.ts
src/adapter/onebot/v12/typed.ts
src/adapter/onebot/v12/utils.ts
src/driver/websocket-client/index.ts
src/views/SettingStage.vue

添加 OneBot v12 协议支持
resolve #28

✨ 支持 OneBot v12 协议

---

src/adapter/errors.ts
src/adapter/onebot/v11/action.ts
src/adapter/onebot/v12/action.ts

🐛 修复部分错误消息不正确的问题

---

src/adapter/onebot/v11/action.ts

支持隐藏 API —— 快速操作
OneBot v11 不支持快速操作

✨ 支持 OneBot v11 隐藏 API

---

src/adapter/adapter.ts

✨ 添加动作处理器的处理日志

---

src/adapter/onebot/v11/action.ts

使用 `user_id` 与 `group_id` 进行判断
当 `send_msg` API 缺少 `message_type` 参数时，无法正确判断消息类型

🐛 修复 OneBot v11 的 `send_msg` API 处理错误

---

src/components/SelectUserList.vue

💄 优化选择用户列表的样式

---

src-tauri/src/utils.rs

修改了 file url 的正则表达式
在 Linux 下无法正确找到文件路径

🐛 修复文件 url 正则表达式的错误

---

src/adapter/behav.ts

清除消息末尾所有的空白字符（空格、tab、不换行空格等）以及所有行终止符字符（如 LF、CR 等）
与某即时通讯平台行为不一致

✨ 修剪消息末尾的空白字符

---

src/adapter/onebot/v11/message.ts

🐛 修复 OneBot v11 提及消息段目标转换错误

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/utils.rs

使用 url 库解决此问题
file uri 转换 path 错误

🐛 修复 file uri 解析不正确的问题

---

src/components/ChatMessage.vue

当为 bot 消息时，不触发重发行为
点击 bot 消息的发送状态按钮时，会错误重发 bot 消息

🐛 修复快速重发可在 bot 消息上触发的问题

---

src/components/ChatContactItem.vue

在群组消息速览显示用户名
群消息速览没有显示发送用户名，当群成员过多时无法区分

✨ 群组消息速览显示用户名

---

src/components/MessageContent.vue

常量 `INIT_SCALE` 修改为 `getWindowSize` 函数的参数
`getWindowSize` 函数添加返回类型

♻️ 重构 MessageContent 组件中的 `getWindowSize` 函数

---

src/adapter/behav.ts
src/adapter/onebot/v11/action.ts
src/stores/chat.ts

♻️ ChatStore 添加 `getMessage` 方法

---

package.json
pnpm-lock.yaml
src/components/MessageContent.vue

使用 linkifyjs 查找纯文本中的链接并将其转换为 HTML <a> 标签

✨ 高亮显示消息文本中的链接

---

src/components/ChatMessage.vue

使用 `computed` 替换 `ref`
1. 聊天消息丢失响应性，造成多个会话间的聊天消息混合
2. 用户权限存在缓存，导致多个会话间的用户权限显示错误

🐛 修复聊天消息丢失响应性的问题

---

src/App.vue

💄 在生产环境下禁用右键菜单

---

src/adapter/onebot/v11/action.ts

修复了 OneBot 11 的动作请求 `get_group_member_info` 和 `get_group_member_list` 的类型错误
部分动作请求由于类型错误，无法正确从数据库中获取数据

🐛 修复 OneBot 11 部分动作请求的类型错误

---

package.json
pnpm-lock.yaml

⬆️ Update tauri-apps

---

src/style.css

💄 去除原始事件底部空白边距

---

src-tauri/src/server.rs
src-tauri/src/utils.rs

当默认端口（8720）被占用时，自动选择未使用的端口
支持多开

✨ 支持自动选择未占用的端口

---

src/components/CreateUserForm.vue

创建用户时无法正常更改用户名，每次输入光标都会跳转到字首
不是很懂为什么这个form要用contenteditable的div来做，虽然看到了屎山标记🤔，如果你同意我或许可以重写一下这部分

🐛 创建用户修改名称以及id时光标跳转

---

src/driver/websocket-client/index.ts

修复了在配置访问令牌时无法连接到 OneBot v11 应用端的问题
resolve #126

🐛 修复 OneBot v11 访问令牌的连接问题

---

src/components/Avatar.vue
src/components/ChatAction.vue
src/components/ChatBox.vue
src/components/ChatBoxTopbar.vue
src/components/ChatContactItem.vue
src/components/ChatInput.vue
src/components/ChatMessage.vue
src/components/ChatNotice.vue
src/components/ChatRequest.vue
src/components/CreateGroupForm.vue
src/components/CreateMemberForm.vue
src/components/CreateUserForm.vue
src/components/HighlightCode.vue
src/components/MessageContent.vue
src/components/SelectUserList.vue
src/components/TimeSeparator.vue
src/components/WaveAudioPlayer.vue
src/views/window/PreviewWindow.vue

将 `defineProps` 修改为 `$defineProps`
迁移到 Vue Marcos 时未修改 `defineProps`，导致 Props  解构后丢失响应性

🐛 修复响应式 Props 解构失效

---

src/views/settings/connect.vue

💄 设置表单添加动画效果

---

src/driver/websocket-client/index.ts
src/stores/connect-settings.ts
src/views/settings/connect.vue

✨ 允许配置连接错误显示

---

src/driver/websocket-client/index.ts

🐛 修复断开连接时自动重连没有停止的问题

---

src/components/chat/ChatBoxHeader.vue

✨ 添加聊天栏头部按钮提示

---

src/components/AppSidebar.vue
src/components/ui/controls/WindowControls.vue

provide的osType为响应式数据
resolve #174

🐛 修复macos下的状态栏显示

---

src/layouts/default.vue

🐛 修复弹窗与消息的层级问题

---

package.json
pnpm-lock.yaml
src/components/AppSidebarManageButton.vue
src/components/CheckUpdateDialog.vue
unocss.config.ts

✨ 显示详细更新日志

---

src/driver/websocket-client/index.ts

🐛 修复连接时没有发出元事件的问题

---

.eslintrc.json
src/components/chat/GroupCreateFormDialog.vue

在建群时添加 ”Bot 自动加入“ 的选项
省去建群后邀请 Bot 的操作

✨ 支持 Bot 自动加入群聊

---

src/components/chat/ChatMessageElementImage.vue
src/views/preview/image.vue

🐛 修复打开图片时可能打开其他图片的问题

---

src/components/chat/ChatDetailsInfoBot.vue

点击右侧信息栏中的连接状态按钮即可刷新连接
作为 #202 的临时解决方案

✨ 添加快速刷新连接按钮

---

src/components/chat/ChatMessageElement.vue

🏷️ 修复 `ChatMessageElement` 组件中的索引类型错误

---

src/adapter/onebot/v11/message.ts
src/adapter/onebot/v12/message.ts
src/auto-imports.d.ts
src/components/chat/ChatMessage.vue
src/components/chat/ChatMessageElementLink.vue
src/components/chat/ChatMessageElementText.vue
src/stores/general-settings.ts
src/utils/chat.ts
src/views/settings/general.vue

- 支持解析文本中的链接
- 添加链接预览开关（默认启用）
- 支持预览链接
方便跳转和预览链接

✨ 添加链接解析与预览

---

src-tauri/src/utils.rs

🐛 修复获取文件时由于错误的文件源导致的闪退

---

src/components/chat/ChatDetailsInfoBot.vue

💄 添加刷新连接图标

---

src-tauri/src/lib.rs
src/App.vue

✨ 将日志打印到 webview 控制台

---

src/driver/websocket-client/index.ts

修复 WebSocket 客户端在服务器反复重启时出现多个重复连接的问题，主要改动：
- 🛠️ **重连定时器管理**：通过 `reconnectTimer` 变量跟踪定时器，每次重连前清除旧的定时器
- 🔒 **连接状态锁**：新增 `isConnecting` 标志防止并发连接
- 🧹 **资源清理优化**：
- 在 `stop()` 和 `autoReconnection()` 中主动清理重连定时器
- 连接前强制断开旧连接 (`connect()` 中调用 `disconnect()`)
当 WebSocket 服务器反复重启时，客户端会出现以下问题：
1. 多个 `setTimeout` 定时器堆积导致重复连接
2. 未关闭的旧连接与新连接同时存在
3. 显式停止后残留定时器仍可能触发重连
此 PR 通过规范化连接生命周期管理，确保：
- 同一时间只有 1 个活跃连接
- 服务器重启时按固定间隔单次重试
- 显式停止后完全释放资源
resolve #222

🐛 修复 WebSocket 重连时出现的重复连接问题

---

src/views/settings/connect.vue

当数据协议变化时，不重启适配器。
数据协议变化时，应该更换适配器，而不是重启现有的适配器。
目前在切换数据协议后，会启动新的适配器，同时之前的适配器会被重启，导致同时存在两个适配器。

🐛 修复切换数据协议时错误重启适配器的问题

---

src/driver/websocket-client/index.ts
src/stores/connect-settings.ts
src/views/settings/connect.vue

✨ 新增自动重连配置

---

src/components/chat/ChatBoxInputBox.vue

:bug: 修复提及菜单中回车意外发送消息的问题

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/lib.rs
src/App.vue

🚸 生产模式下禁用默认浏览器快捷键

---

src/adapter/behav.ts
src/auto-imports.d.ts
src/components/FileCard.vue
src/components/chat/ChatBoxInput.vue
src/components/chat/ChatBoxInputBox.vue
src/components/chat/ChatBoxInputFileButton.vue
src/components/chat/ChatContactsList.vue
src/components/chat/ChatContactsListItem.vue
src/components/chat/ChatContactsListItemMenu.vue
src/components/chat/ChatDetailsInfoGroup.vue
src/database/db.ts
src/stores/modal.ts
src/stores/state.ts
src/utils/chat.ts
src/views/chat/[chatType].[chatId].vue
vite.config.ts

♻️ 改进自动类型导入

---

src/components/chat/GroupCreateFormDialog.vue
src/components/chat/GroupEditFormDialog.vue
src/components/chat/UserCreateFormDialog.vue
src/components/chat/UserEditFormDialog.vue

💄 调整表单标签文本位置

---

src/utils/chat.ts

现在获取的消息 ID，为当前的秒级时间戳。
如果在同一秒内多次调用，则会递增 ID
resolve #242

🐛 修复重启前后消息 ID 不唯一的问题
